name: Main Job

on:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: ShaunLWM/actions-i18-coverage@latest
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
